//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wather
    {
        public int Id { get; set; }
        public int EmployeId { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Task Task { get; set; }
    }
}
